routes/web.php
<?php

use Illuminate\Support\Facades\Route;



Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'BackendlayoutController@index')->name('admin.home');

    Route::resource('clientes', 'admin\ClientesController');

    Route::resource('produtos', 'admin\ProdutosController');

    Route::resource('assinaturas', 'admin\AssinaturasController');

    Route::resource('perguntas', 'admin\PerguntasController');

    Auth::routes();
});


//SISTEMA ROUTES

Route::group(['prefix' => 'sistema'], function(){
    Route::get('/', 'sistema\SistemaController@index')->name('sistema.home');

});


//SISTEMA ROUTES


//FRONTEND ROUTES

Route::get('/', 'FrontendController@index')->name('frontend.home');
Route::get('/conheca', 'FrontendController@conheca')->name('frontend.conheca');
Route::get('/como-funciona', 'FrontendController@comofunciona')->name('frontend.comofunciona');
Route::get('/beneficios', 'FrontendController@beneficios')->name('frontend.beneficios');

Route::get('/adquira', 'FrontendController@adquira')->name('frontend.adquira');
Route::get('/suporte', 'FrontendController@suporte')->name('frontend.suporte');


//LOGIN SCREEn
Route::get('/acesse', 'FrontendController@acesse')->name('frontend.acesse');

resources/views/layouts/backend/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/flexbox.js') }}" defer></script>
    <script src="{{ asset('js/fontawesome.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/fontawesome.css') }}" rel="stylesheet">
    <link href="{{ asset('css/flexboxgrid.css') }}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700&display=swap" rel="stylesheet">

</head>
<body>
    <div class="container-fluid bg-dark-blue">
        <div class="row">
            @include('layouts.backend.navbar')
            <div class="col-md-10 sistema-content">
                @yield('content')
            </div>
        </div>
    </div>
</body>
</html>

resources/views/layouts/backend/footer.blade.php
<footer class="bg-custom-blue">
    <div class="container">

        <nav class="navbar navbar-expand-lg ">
                <div class="col-md-3">
                    <a class="navbar-brand" href="/">
                        <img src="{{asset('images/logowhite.png') }}" class="img-fluid">
                    </a>
                </div>
                <div class="col-md-9">
                    <div class=" float-right" id="">
                      <div class="navbar-nav navbar-color">
                        <a class="nav-item nav-link" href="#">HOME <span class="sr-only">(current)</span></a>
                        <a class="nav-item nav-link" href="#">CONHEÇA</a>
                        <a class="nav-item nav-link" href="#">COMO FUNCIONA</a>
                        <a class="nav-item nav-link" href="#">BENEFÍCIOS</a>
                        <a class="nav-item nav-link" href="#">SUPORTE</a>
                      </div>
                    </div>
                </div>
          </nav>
          <div class="col-md-12">
              <div class="float-right"><a href="" class="">suporte@meusregistrosmedicos.com.br</a></div>
              <div class="clearfix"></div>
          </div>
        <!-- NAVBAR  -->
    </div>
</footer>

resources/views/layouts/backend/header.blade.php
<header class='header-container bg-blue'>

    <div class="">
        <nav class="navbar navbar-expand-lg ">
            <div class="col-md-3">
                <a class="navbar-brand" href="/">
                    <img src="{{asset('images/logowhite.png') }}" class="img-fluid">
                </a>
            </div>
            <div class="col-md-9">
                <div class="collapse navbar-collapse  float-right" id="navbarNavAltMarkup">
                  <div class="navbar-nav navbar-color"><a class="nav-item nav-link small" href="#">Página Inicial</a></div>
                  <div class="navbar-nav navbar-color"><a class="nav-item nav-link small" href="#">Meus Dados</a></div>
                  <div class="navbar-nav navbar-color"><a class="nav-item nav-link small" href="#">Suporte</a></div>
                  <div class="navbar-nav navbar-color"><a class="nav-item nav-link small" href="#">Sair</a></div>
                </div>
            </div>
          </nav>

    </div>

</header>

resources/views/layouts/backend/navbar.blade.php
<div class="col-md-2">
    <div class="sidebar-container">
        <div class="sidebar">

            <img src="{{asset('images/logowhite.png') }}" class="img-fluid">
            <div class="spacer"></div>
            <ul class="sistema-navbar">

                @guest()
                <li class="sistema-navbar-item"><a href="{{route('login')}}" class="sistema-navbar-item-link">Acessar</a></li>
                <li class="sistema-navbar-item"><a href="{{route('register')}}" class="sistema-navbar-item-link">Cadastrar</a></li>





                @else
            <li class="sistema-navbar-item"><a href="{{route('home')}}" class="sistema-navbar-item-link">Inicio</a></li>


            <li class="sistema-navbar-item">

                <a class="sistema-navbar-item-link" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Sair') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>

            </li>



            <li class="sistema-navbar-item"><a href="{{route('clientes.index')}}" class="sistema-navbar-item-link">Clientes</a></li>
            <li class="sistema-navbar-item"><a href="{{ route('produtos.index') }}" class="sistema-navbar-item-link">Produtos</a></li>
            <li class="sistema-navbar-item"><a href="{{ route('assinaturas.index') }}" class="sistema-navbar-item-link">Assinaturas</a></li>
            <li class="sistema-navbar-item"><a href="{{ route('perguntas.index') }}" class="sistema-navbar-item-link">Perguntas Frequentes</a></li>

                @endguest()
            </ul>
        </div>
    </div>
</div>