routes/web.php
<?php

use Illuminate\Support\Facades\Route;



Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'BackendlayoutController@index')->name('admin.home');

    Route::resource('clientes', 'admin\ClientesController');

    Route::resource('produtos', 'admin\ProdutosController');

    Route::resource('assinaturas', 'admin\AssinaturasController');

    Route::resource('perguntas', 'admin\PerguntasController');

    Auth::routes();
});


//SISTEMA ROUTES

Route::group(['prefix' => 'sistema'], function(){
    Route::get('/', 'sistema\SistemaController@index')->name('sistema.home');

});


//SISTEMA ROUTES


//FRONTEND ROUTES

Route::get('/', 'FrontendController@index')->name('frontend.home');
Route::get('/conheca', 'FrontendController@conheca')->name('frontend.conheca');
Route::get('/como-funciona', 'FrontendController@comofunciona')->name('frontend.comofunciona');
Route::get('/beneficios', 'FrontendController@beneficios')->name('frontend.beneficios');

Route::get('/adquira', 'FrontendController@adquira')->name('frontend.adquira');
Route::get('/suporte', 'FrontendController@suporte')->name('frontend.suporte');


//LOGIN SCREEn
Route::get('/acesse', 'FrontendController@acesse')->name('frontend.acesse');

app/Assinatura.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Assinatura extends Model
{
    public function clientes(){

        return $this->belongsTo('App\Cliente');
    }

    public function produtos(){
        return $this->belongsTo('App\Produto');
    }
}

app/Http/Controllers/admin/AssinaturasController.php
<?php

namespace App\Http\Controllers\admin;

use App\Assinatura;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AssinaturasController extends Controller
{
    public function index(){
        $assinaturas = Assinatura::all();

        return view('backend.assinaturas.index')->with('assinaturas', $assinaturas);
    }
    public function show($id){

        $assinatura = Assinatura::find($id);

        return view('backend.assinaturas.show')->with('assinatura', $assinatura);
    }
}

resources/views/backend/assinaturas/index.blade.php
@extends('layouts.backend.app')

@section('content')
@include('backend.utilities.flash')

<h2 class="page-title">Lista de Assinaturas</h2>

<table class="table table-hover ">
    <thead class="thead-blue">
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Protuto</th>
        <th scope="col">Inicio</th>
        <th scope="col">Fim</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody class="table-custom">
        @foreach ($assinaturas as $assinatura )
        <tr>
            <td >{{$assinatura->clientes->nomecompleto}}</td>
            <td >{{$assinatura->produtos->titulo}}</td>
            <td>{{$assinatura->inicio}}</td>
            <td>{{$assinatura->fim}}</td>
            <td>
                <a href="{{route('assinaturas.show',$assinatura->id)}} " class="btn btn-success">Visualizar</a>
                <a href="{{route('assinaturas.edit',$assinatura->id)}}" class="btn btn-info">Editar</a>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>








@endsection

resources/views/backend/assinaturas/show.blade.php
@extends('layouts.backend.app')

@section('content')
@include('backend.utilities.flash')

<h2 class="page-title">Lista de Assinaturas</h2>

<table class="table table-hover ">
    <thead class="thead-blue">
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Protuto</th>
        <th scope="col">Inicio</th>
        <th scope="col">Fim</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody class="table-custom">
        <tr>
            <td >{{$assinatura->clientes->nomecompleto}}</td>
            <td >{{$assinatura->produtos->titulo}}</td>
            <td>{{$assinatura->inicio}}</td>
            <td>{{$assinatura->fim}}</td>
            <td>
                <a href="{{route('assinaturas.edit',$assinatura->id)}}" class="btn btn-info">Editar</a>
            </td>
        </tr>
    </tbody>
  </table>








@endsection